function gvjs_$X(a,b){gvjs_aU.call(this,a,b)}gvjs_p(gvjs_$X,gvjs_aU);gvjs_=gvjs_$X.prototype;gvjs_.Pp=function(a){a.style(gvjs_Kx,0).style(gvjs_Lx,1).style(gvjs_Ix,.4).style(gvjs_Jx,2);return a};gvjs_.lr=function(a){a.style(gvjs_Kx,null).style(gvjs_Lx,null).style(gvjs_Ix,null).style(gvjs_Jx,null);return a};gvjs_.vS=function(a){var b=a.data().value.color;this.Pp(a).style(gvjs_1u,b)};gvjs_.oS=function(a){var b=a.data().value.color;this.Pp(a).style(gvjs_1u,gvjs_bU(b,this.cP,this.nB))};
gvjs_.lS=function(a){var b=a.data().value.color;this.lr(a).style(gvjs_1u,gvjs_cU(b,this.jea,this.nB))};gvjs_.uS=function(a){var b=a.data().value.color;this.lr(a).style(gvjs_1u,b)};function gvjs_aY(a){this.m=a.options;this.DW=a.jn;this.Dh=a.HJ;this.tN=a.axes.domain;this.c3=a.axes.target;this.T9=null!=a.S9?a.S9:1;this.voa=null!=a.uoa?a.uoa:gvjs_0;this.Xv=this.layout()}gvjs_aY.prototype.Iy=function(){var a=[];gvjs_s(this.Xv,function(b){gvjs_5c(a,b.D.list)});gvjs_ad(a,function(a,c){return a.stack===c.stack?-gvjs_$c(a.xo,c.xo):gvjs_$c(a.stack,c.stack)});return a};
gvjs_aY.prototype.OH=function(){var a=[];gvjs_s(this.Xv,function(b){gvjs_q(b.groups,function(b,d){null!=b&&gvjs_q(b.eo,function(b,c){gvjs_5c(a,gvjs_r(b.Rb.pk,function(a,b){var e=a.shape.data();return a.shape.clone().data({value:e,id:gvjs_3L(gvjs_3L(gvjs_3L(gvjs_3L(gvjs_5L(a.definition.co,a.definition.KE),gvjs_US,a.definition.dj),gvjs_rv,d),gvjs_Zx,c),gvjs_TS,b+1)})}));gvjs_5c(a,gvjs_r(b.Rb.Ez,function(a,b){var e=a.shape.data();return a.shape.clone().data({value:e,id:gvjs_3L(gvjs_3L(gvjs_3L(gvjs_3L(gvjs_5L(a.definition.co,
a.definition.KE),gvjs_US,a.definition.dj),gvjs_rv,d),gvjs_Zx,c),gvjs_TS,-b-1)})}))},this)},this)},this);return a};function gvjs_xka(a,b){if(1>=a)return[b];var c=0*(b.end-b.start),d=c/(a-1);c=(b.end-b.start-c)/a;var e=[];b=b.start;for(var f=0;f<a;f++)e.push(new gvjs_x(b,b+c)),b+=c+d;return e}
function gvjs_yka(a,b,c,d){var e={range:b,definition:c,eo:[]},f=gvjs_xka(c.eo.length,b);gvjs_q(c.eo,function(a,b){var c={definition:a,range:f[b],height:{pk:0,Ez:0},Rb:{pk:[],Ez:[]}};e.eo.push(c);gvjs_q(a.Rb,function(a,e){a.co in d.index?d.list[d.index[a.co]].Rb.push(a):(d.index[a.co]=d.list.length,d.list.push({color:null,Wb:a.co,stack:b,xo:e,Rb:[a]}),d.K2=Math.max(d.K2,b+1),d.OU=Math.max(d.OU,e+1));e=this.c3[a.QK];var f=e.scale,g=f.scale(f.eC());f=c.range.start;var h=c.height.pk+g,k=c.range.end-c.range.start,
l=a.value;if(isNaN(l)||null==l)e=null;else{l-=g;var m=l+c.height.pk;0<=l?c.height.pk+=l:(h=-c.height.Ez+g,m=-c.height.Ez+l+g,c.height.Ez-=l);a.Vt=k/2+c.range.start;a.dDa=m;gvjs_3L(gvjs_5L(a.co,a.KE),gvjs_US,a.dj);g=new gvjs_w(h,f+k,h+l,f);g.top>g.bottom&&(m=g.top,g.top=g.bottom,g.bottom=m);null===e.range?e.range=new gvjs_x(g.top,g.bottom):(gvjs_xf(e.range,g.top),gvjs_xf(e.range,g.bottom));e=(new gvjs_iA(f,h,k,l)).setData(a)}e&&(0<=gvjs_E(gvjs_eA(e),gvjs_mb)?c.Rb.pk:c.Rb.Ez).push({definition:a,shape:e})},
this)},a);return e}
function gvjs_zka(a,b){var c={};if(gvjs_Sc(a,function(a){return 0===a.groups.length}))return{};gvjs_q(a,function(a,b){gvjs_q(a.groups,function(a){c[a.dj]=b})});var d={},e={},f;for(f in b){var g=b[f],h=g.scale;g=gvjs_r(g.columns,function(b){return a[c[b]]});var k={oCa:h.wi(),type:g[0].type,scale:h,eg:{},groups:[]};e[f]=k;k.type in d||(d[k.type]=f);if(h.wi())for(var l=0;;l++){var m={eo:[]},n=gvjs_r(g,function(a){return a.groups[l]});if(!gvjs_Rc(n,gvjs_8b))break;gvjs_q(n,function(a){a.Wg&&null==m.Wg&&
(m.Wg=a.Wg);gvjs_5c(m.eo,a.eo)});k.groups.push(m)}else{var p=[];gvjs_q(g,function(a){gvjs_q(a.groups,function(a){var b=gvjs_8c(p,a,function(a,b){return h.Ox(a.Wg,b.Wg)});0>b?gvjs__c(p,{Wg:a.Wg,eg:gvjs_t(a.eg),eo:gvjs_4c(a.eo)},-(b+1)):gvjs_5c(p[b].eo,a.eo)})});k.groups=p}}return e}
function gvjs_Aka(a,b,c,d){var e=a.tN[c],f=e.scale;f.wi()||gvjs_ad(b.groups,function(a,b){a=a.ia?a.Wg:f.scale(a.Wg);b=b.ia?b.Wg:f.scale(b.Wg);return gvjs_$c(a,b)});var g=Infinity,h=null;gvjs_q(b.groups,function(a){f.wi()&&(a.Wg=f.add(a.Wg),a.ia=!0);a=a.ia?a.Wg:f.scale(a.Wg);if(null!=a){if(null!==h){var b=a-h;0<b&&b<g&&(g=b)}h=a}});isFinite(g)||(g=1);var k={list:[],index:{},K2:0,OU:0};c=gvjs_r(b.groups,function(a){var b=a.ia?a.Wg:f.scale(a.Wg);if(null!=b){var c=g,d=b;b+=c;switch(this.voa){case gvjs_0:d-=
c/2,b-=c/2}c=(b-d)/2;d+=(1-this.T9)*c;b-=(1-this.T9)*c;d=new gvjs_x(d,b);null===e.range?e.range=d.clone():(c=e.range,c.start=Math.min(c.start,d.start),c.end=Math.max(c.end,d.end));return gvjs_yka(this,d,a,k)}},a);for(var l=0,m=k.K2;l<m;l++)for(var n=0,p=k.OU;n<p;n++)a.Dh.xu(String(l),String(n));var q=a.Dh.tf();gvjs_q(k.list,function(a,b){var c=gvjs_vd(gvjs_C(this.m,gvjs_Hx+(b+d)+".color",q.Dq(a.stack,a.xo))).ec;a.color=c;gvjs_q(a.Rb,function(a){a.color=c})},a);return{definition:b,D:k,groups:c}}
gvjs_aY.prototype.layout=function(){var a=gvjs_zka(this.DW,this.tN),b=0;return gvjs_2d(a,function(a,d){a=gvjs_Aka(this,a,d,b);b+=a.D.list.length;return a},this)};function gvjs_bY(a,b,c,d){gvjs_pU.call(this,a,b,c,d)}gvjs_p(gvjs_bY,gvjs_pU);gvjs_bY.prototype.ij=function(){return gvjs_C(this.options,gvjs_pt,gvjs_4,gvjs_KT)===gvjs_2?gvjs_4:gvjs_2};
gvjs_bY.prototype.$la=function(a,b,c,d){function e(a,b){return f?b:a}var f=gvjs_D(this.options,"stacked",!1),g=this.cj,h=a[String(c.dj)],k=g.getValue(d,c.dj);this.ij();var l=e([0],c.D),m=[];gvjs_q(e(c.D,[0]),function(a){var e=[],n={};gvjs_q(l,function(l){l=(f?l:a).As;var m=g.getValue(d,l),p=b[l],q=p.scale,r=p.name;r in n||(e.push({Rb:[]}),n[r]=e.length-1);r=e[n[r]].Rb;q.wi()&&null!=m&&(0===gvjs_fT(q).length&&q.add("",!0),q.add(m,!0));r.push({dj:c.dj,co:l,KE:d,uN:h.name,QK:p.name,Wg:k,oDa:m,color:null,
value:p.scale.scale(m),ia:!0})});gvjs_q(e,function(a){m.push(a)})});return{dj:c.dj,Wg:k,eg:c.eg,eo:m}};gvjs_bY.prototype.Zla=function(a,b,c){return{type:this.cj.X(c.dj),eg:c.eg,groups:gvjs_r(gvjs_ed(this.cj.da()),gvjs_o(this.$la,this,a,b,c))}};
gvjs_bY.prototype.CX=function(a,b,c){gvjs_s(a,function(a){a.expand=!1});gvjs_s(b,function(a){a.expand=!0});var d=this.ij()===gvjs_4,e=d&&gvjs_Rc(gvjs_8d(b),function(a){return b[a].zk===gvjs_uy}),f=d&&gvjs_Rc(gvjs_8d(b),function(a){return b[a].zk===gvjs_zt}),g={},h;for(h in b)gvjs_q(b[h].columns,function(a){g[a]={name:h,scale:b[h].scale}});var k={};for(h in a)gvjs_q(a[h].columns,function(b){k[b]={name:h,scale:a[h].scale}});var l=gvjs_r(this.dN.jn,gvjs_o(this.Zla,this,k,g));return new gvjs_aY({options:this.options,
jn:l,axes:{domain:a,target:b},HJ:c,S9:gvjs_vi(this.options,"groupSize"),HCa:!d||e,ICa:!d||f})};function gvjs_cY(a){gvjs_gM.call(this,a)}gvjs_p(gvjs_cY,gvjs_gM);gvjs_=gvjs_cY.prototype;gvjs_.yq=function(){return null};gvjs_.th=function(){return gvjs_LT};gvjs_.gq=function(a,b,c,d){a=new gvjs_XS(this,a,0,c,d);a.Aw([gvjs_lt,gvjs_nv,gvjs_vx,gvjs_FS,gvjs_MS,gvjs_Ls,gvjs_Ks,gvjs_Wi]);return a};gvjs_.Fo=function(a,b){return new gvjs_$X(a,b)};gvjs_.an=function(a,b,c,d){return new gvjs_bY(a,b,c,d)};
gvjs_.ws=function(a){return[new gvjs_5S([new gvjs_1L(gvjs_cs)]),new gvjs_7S([new gvjs_1L(gvjs_ds),new gvjs_1L(gvjs_es)],gvjs_C(a,gvjs_Bx)===gvjs_Sx),new gvjs_6S([new gvjs_1L(gvjs_cs),new gvjs_1L(gvjs_ds),new gvjs_1L(gvjs_es),new gvjs_1L(gvjs_QS)]),new gvjs_9S([new gvjs_1L(gvjs_ds)])]};gvjs_.NG=function(a,b){null!=this.Xg?this.Xg.update(a,b):this.Xg=new gvjs_WA(this.container,a,b,[gvjs_Bs,gvjs_SS])};gvjs_k(gvjs_gk,gvjs_cY,void 0);gvjs_cY.convertOptions=function(a){var b=new gvjs_8h([a]);a=gvjs_RT(a);b=b.Zb(gvjs_Sw);null!=b&&(a.bars=b===gvjs_4?gvjs_2:gvjs_4);return a};gvjs_cY.prototype.draw=gvjs_cY.prototype.draw;gvjs_cY.prototype.clearChart=gvjs_cY.prototype.Vb;gvjs_cY.prototype.getSelection=gvjs_cY.prototype.getSelection;gvjs_cY.prototype.setSelection=gvjs_cY.prototype.setSelection;
